from sqlalchemy import Column, Integer, String, Float, Boolean, DateTime, ForeignKey, Text, JSON
from sqlalchemy.orm import relationship
from app.models.user import Base
from datetime import datetime
import uuid


def gen_code():
    return "AFF" + uuid.uuid4().hex[:6].upper()


class AffiliateProfile(Base):
    """One-to-one extension of User for affiliate-specific data."""
    __tablename__ = "affiliate_profiles"

    id              = Column(Integer, primary_key=True, index=True)
    user_id         = Column(Integer, ForeignKey("users.id"), unique=True, nullable=False, index=True)
    referral_code   = Column(String(20), unique=True, nullable=False, default=gen_code)
    commission_rate = Column(Float, default=20.0)        # percentage
    total_earnings  = Column(Float, default=0.0)
    total_clicks    = Column(Integer, default=0)
    total_sales     = Column(Integer, default=0)
    # Payment info
    upi_id          = Column(String(100), nullable=True)
    bank_name       = Column(String(120), nullable=True)
    account_number  = Column(String(50), nullable=True)
    ifsc_code       = Column(String(20), nullable=True)
    
    # Phase 1 UI New Fields
    display_name         = Column(String(150), nullable=True)
    short_bio            = Column(Text, nullable=True)
    country              = Column(String(100), nullable=True)
    youtube              = Column(String(255), nullable=True)
    instagram            = Column(String(255), nullable=True)
    linkedin             = Column(String(255), nullable=True)
    preferred_categories = Column(JSON, nullable=True)
    promotion_methods    = Column(JSON, nullable=True)
    primary_audience     = Column(String(100), nullable=True)
    audience_size        = Column(String(50), nullable=True)
    preferred_language   = Column(String(50), nullable=True)
    preferred_currency   = Column(String(10), nullable=True)
    timezone             = Column(String(50), nullable=True)
    email_notifications  = Column(Boolean, default=True)

    # Status
    is_active       = Column(Boolean, default=True)
    status          = Column(String(50), default="active")
    created_at      = Column(DateTime, default=datetime.utcnow)
    updated_at      = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    user        = relationship("User",                back_populates="affiliate_profile")
    commissions = relationship("AffiliateCommission", back_populates="affiliate", cascade="all, delete-orphan")
    payouts     = relationship("AffiliatePayout",     back_populates="affiliate", cascade="all, delete-orphan")


class AffiliateCommission(Base):
    """A commission earned when a referred user purchases a product."""
    __tablename__ = "affiliate_commissions"

    id              = Column(Integer, primary_key=True, index=True)
    affiliate_id    = Column(Integer, ForeignKey("affiliate_profiles.id"), nullable=False, index=True)
    order_id        = Column(Integer, ForeignKey("orders.id"), nullable=True)
    product_id      = Column(Integer, nullable=True)
    product_name    = Column(String(255), nullable=True)
    sale_amount     = Column(Float, nullable=False)      # original sale price
    commission_amt  = Column(Float, nullable=False)      # amount earned
    status          = Column(String(20), default="pending")  # pending | approved | paid
    created_at      = Column(DateTime, default=datetime.utcnow)
    updated_at      = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    affiliate = relationship("AffiliateProfile", back_populates="commissions")


class AffiliatePayout(Base):
    """A withdrawal/payout request from an affiliate."""
    __tablename__ = "affiliate_payouts"

    id              = Column(Integer, primary_key=True, index=True)
    affiliate_id    = Column(Integer, ForeignKey("affiliate_profiles.id"), nullable=False, index=True)
    amount          = Column(Float, nullable=False)
    method          = Column(String(30), default="upi")   # upi | bank
    upi_id          = Column(String(100), nullable=True)
    bank_account    = Column(String(50), nullable=True)
    status          = Column(String(20), default="pending")  # pending | completed | rejected
    notes           = Column(Text, nullable=True)
    created_at      = Column(DateTime, default=datetime.utcnow)
    updated_at      = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    affiliate = relationship("AffiliateProfile", back_populates="payouts")


class ReferralLink(Base):
    """A unique referral link generated by an affiliate for a specific product."""
    __tablename__ = "referral_links"

    id            = Column(Integer, primary_key=True, index=True)
    affiliate_id  = Column(Integer, ForeignKey("affiliate_profiles.id"), nullable=False, index=True)
    product_id    = Column(Integer, ForeignKey("products.id"), nullable=False, index=True)
    referral_code = Column(String(50), unique=True, nullable=False, index=True)
    name          = Column(String(100), nullable=True)  # campaign or alias name
    clicks_count  = Column(Integer, default=0)
    is_active     = Column(Boolean, default=True)
    created_at    = Column(DateTime, default=datetime.utcnow)

    affiliate = relationship("AffiliateProfile")
    product   = relationship("Product")
    clicks    = relationship("ReferralClick", back_populates="referral_link", cascade="all, delete-orphan")


class ReferralClick(Base):
    """An individual click tracked for a referral link."""
    __tablename__ = "referral_clicks"

    id               = Column(Integer, primary_key=True, index=True)
    referral_link_id = Column(Integer, ForeignKey("referral_links.id"), nullable=True, index=True)
    affiliate_id     = Column(Integer, ForeignKey("affiliate_profiles.id"), nullable=False, index=True)
    ip_address       = Column(String(45), nullable=True)
    user_agent       = Column(Text, nullable=True)
    clicked_at       = Column(DateTime, default=datetime.utcnow)

    referral_link = relationship("ReferralLink", back_populates="clicks")
    affiliate     = relationship("AffiliateProfile")
